Block Semiring.solve to reduce memory footprint
This commit eliminates the following out-of-memory error when parsing a
string of length 93:
```
Traceback (most recent call last):
  File "fggs/bin/sum_product.py", line 91, in <module>
    zs = fggs.sum_products(fgg, method=args.method, tol=args.tol, kmax=args.kmax)
  File "fggs/fggs/sum_product.py", line 455, in sum_products
    comp_values = SumProduct.apply_to_patterned_tensors(fgg, comp_opts, inputs.keys(), comp_labels, *inputs.values())
  File "fggs/fggs/sum_product.py", line 412, in apply_to_patterned_tensors
    (nonphysicals, *physicals) = SumProduct.apply(
  File "python/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "fggs/fggs/sum_product.py", line 362, in forward
    newton(lambda x: F(fgg, x, inputs, semiring),
  File "fggs/fggs/sum_product.py", line 97, in newton
    dX = multi_solve(JF, F0 - x0)
  File "fggs/fggs/multi.py", line 224, in multi_solve
    b[z].copy_(a[z,z].solve(b[z], semiring))
  File "fggs/fggs/indices.py", line 1305, in solve
    x = semiring.solve(dense_a, dense_b)
  File "fggs/fggs/semirings.py", line 142, in solve
    return Semiring.solve(self, a, b)
  File "fggs/fggs/semirings.py", line 83, in solve
    a[:,k+1:] = self.add(a[:,k+1:], self.mul(a[:,k,None], a[k,k+1:]))
  File "fggs/fggs/semirings.py", line 107, in mul
    return x.mul(y).nan_to_num_(nan=0., posinf=inf)
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 10207632960 bytes. Error code 12 (Cannot allocate memory)
```

Unfortunately we can't use `addcmul_` because we need `nan_to_num_`

To do: allow setting `block_size` instead of `AUTOMATIC_BLOCK_SIZE`